### PR TITLE
New embedding models

### PR DESCRIPTION
**Pull request by bfoujols**
**25 january 2024** : New embedding models 

OpenAI has 2 new models that can be used to generate embeddings. More information on the [OpenAI Blog](https://openai.com/blog/new-embedding-models-and-api-updates).

Status | Model                  | Embedding size  |
-----|------------------------|-----------------|
Default | text-embedding-ada-002 | 1536            | 
New | text-embedding-3-small | 512 or 1536     | 
New | text-embedding-3-large | 256 or 1024 or 3072 |

### CODE REVIEW

**Comment by bfoujols** [comment]
Currently, the code is only compatible for length 1536, only the new model "text-embedding-3-small" can run with Doctrine and Qdrant.

**Comment by simpleenigma** [comment]
Can you put a 1536 size vector on the large model so that we can use the same size we already have in our vector store?

**Comment by MaximeThoonsen** [comment]
Thanks @bfoujols,

I added an issue : https://github.com/theodo-group/LLPhant/issues/72 so we can work on it

**Comment by MaximeThoonsen** [comment]
@bfoujols I think something went wrong somewhere as I merged only one commit.

**Pull request merged**
