### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by f-lombardo**

### CODE REVIEW

**Comment by MaximeThoonsen** [comment]
Hey @f-lombardo, did you test them so they don't crash?

**Comment by f-lombardo** [comment]
Hey @MaximeThoonsen , I did, and I think the question of one of the examples is a bit outdated, so in my last commit I proposed a new one.
During my experiments with the original question sometimes I've got this error:
```
Warning: Undefined array key "description" in /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Experimental/Agent/TaskManager.php on line 21

Fatal error: Uncaught TypeError: LLPhant\Experimental\Agent\Task::__construct(): Argument #2 ($description) must be of type string, null given, called in /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Experimental/Agent/TaskManager.php on line 21 and defined in /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Experimental/Agent/Task.php:11
Stack trace:
#0 /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Experimental/Agent/TaskManager.php(21): LLPhant\Experimental\Agent\Task->__construct('Document Source...', NULL)
#1 /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Chat/OpenAIChat.php(333): LLPhant\Experimental\Agent\TaskManager->addTasks(Array)
#2 /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Chat/OpenAIChat.php(290): LLPhant\Chat\OpenAIChat->callFunction('addTasks', Array)
#3 /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Chat/OpenAIChat.php(64): LLPhant\Chat\OpenAIChat->handleTools(Object(OpenAI\Responses\Chat\CreateResponse))
#4 /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Experimental/Agent/CreationTaskAgent.php(62): LLPhant\Chat\OpenAIChat->generateText('You are a task ...')
#5 /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Experimental/Agent/AutoPHP.php(48): LLPhant\Experimental\Agent\CreationTaskAgent->createTasks('Find the name o...', Array)
#6 /var/llphant/examples/get-web-page-autoPHP/script.php(17): LLPhant\Experimental\Agent\AutoPHP->run()
#7 {main}
  thrown in /var/llphant/examples/get-web-page-autoPHP/vendor/theodo-group/llphant/src/Experimental/Agent/Task.php on line 11
```

**Comment by f-lombardo** [comment]
See #169

**Comment by MaximeThoonsen** [comment]
Ok thanks again @f-lombardo !

**Pull request merged**
