### PR TITLE
Ollama Embedding provider

### PR DESCRIPTION
**Pull request by npotier**
Hello, 

This is my first contribution on this project and I would like to propose the usage of **ollama** as an **Embedding Generator**.

This PR is mainly about a new Class `OllamaEmbeddingGenerator.php` that implements the `EmbeddingGeneratorInterface` and make an API Call to Ollama embedding endpoint.

### CODE REVIEW

**Comment by MaximeThoonsen** [comment]
Hello @npotier ,
Thanks for your PR! Few comments :

- for now, we only support OpenAI, so it would start a not-so-little change ;)
- because OpenAI embeddings have 1536 dimensions, this PR needs to add a dynamic length for embeddings like in the `DoctrineEmbeddingEntityBase` class and `QdrantVectorStore` class.

**Comment by ezimuel** [comment]
@MaximeThoonsen I just sent [a proposal](https://github.com/theodo-group/LLPhant/pull/76) for supporting other LLMs using Ollama. I think we can add the embedding support as @npotier proposed.

**Comment by arnaudgoulpeau** [comment]
@npotier do you plan to resolve conflicts ? I can help if you want it. Thanks !

**Comment by arnaudgoulpeau** [comment]
@npotier I created another PR for this feature, hope it does not upset you.

https://github.com/theodo-group/LLPhant/pull/84

**Comment by MaximeThoonsen** [comment]
Hey @npotier , I'm closing this one because I merged the work of Arnaud.

**Comment by npotier** [comment]
Hello @arnaudgoulpeau thanks for your rework, and i'm not upset about it ;)

**Pull request closed without merging**
