### PR TITLE
fix doctrine vector store

### PR DESCRIPTION
**Pull request by chr-hertel**
Not sure if it's me, but I needed that extra line to make it work.

Am I getting sth wrong?

### CODE REVIEW

**Comment by MaximeThoonsen** [comment]
hey @chr-hertel, can I see your code and the error you get?

**Comment by chr-hertel** [comment]
Basically just

> An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "pgembedding" of relation "page" violates not-null constraint

and the code:
```php
    foreach ($finder->getIterator() as $file) {
            $reader = new FileDataReader($file->getPath(), Page::class);

            $documents = $reader->getDocuments();

            $splittedDocuments = DocumentSplitter::splitDocuments($documents, 800);

            // step is optional based on the docs
            // https://github.com/theodo-group/LLPhant#embedding-formatter
            $formattedDocuments = EmbeddingFormatter::formatEmbeddings($splittedDocuments);

            $embededDocuments = $this->embeddingGenerator->embedDocuments($formattedDocuments);

            $vectorStore = new DoctrineVectorStore($this->em, Page::class);
            $vectorStore->addDocuments($embededDocuments);
        }
```

The `Page` class basically is empty right now.

**Comment by MaximeThoonsen** [comment]
does the Page class extends DoctrineEmbeddingEntityBase?

**Comment by MaximeThoonsen** [comment]
There is a working example here: https://github.com/theodo-group/LLPhant/blob/main/tests/Integration/Embeddings/VectorStores/Doctrine/DoctrineVectorStoreTest.php

**Comment by MaximeThoonsen** [comment]
Your code should work, I'm looking for the potential bug

**Comment by MaximeThoonsen** [comment]
You are right there is a bug that the test doesn't catch

**Comment by chr-hertel** [comment]
While investigating I found that the vector is written to `Document::$embedding` as an array, but didn't find the place where it is converted into the string for `DoctrineEmbeddingEntityBase::$pgembedding`

**Comment by chr-hertel** [comment]
the better solution might be to write a DBAL type instead :thinking:

**Comment by MaximeThoonsen** [comment]
I think I made a bad refacto at some point in the past..
Well I agree with your fix, thanks! And sorry for the lost time.
And yes we can create a better solution with a DBAL type instead

**Comment by MaximeThoonsen** [comment]
can you fix the style and I merge ?

**Comment by chr-hertel** [comment]
No worries at all @MaximeThoonsen! Thanks for the super fast support!

**Comment by MaximeThoonsen** [comment]
@chr-hertel your code is released in the last version (0.2.8).

**Pull request merged**
