### PR TITLE
Ollama Embedding Generator

### PR DESCRIPTION
**Pull request by arnaudgoulpeau**
I know there is already a PR for this. I took the code from @npotier and used the already existing `OllamaConfig`.

I also added a test for the generator, as no one were created before for OpenAI or Mistral.

### CODE REVIEW

**Comment by MaximeThoonsen** [comment]
Nice work. I'll wait for the styling fixes and then I'll merge

**Comment by arnaudgoulpeau** [comment]
@MaximeThoonsen PR ready

**Comment by MaximeThoonsen** [comment]
do you have linkedin or twitter ?

**Comment by arnaudgoulpeau** [comment]
I sent you an email !

**Pull request merged**
