### PR TITLE
Add speech-to-text functionality for OpenAI

### PR DESCRIPTION
**Pull request by f-lombardo**

### CODE REVIEW

**Comment by MaximeThoonsen** [comment]
Nice ! Thanks @f-lombardo !

**Comment by ClicShopping** [comment]
Hello,
Just Question I implement this with my own approach and js to have a realtime transcription (delay 5 second)
Can we have a translation in relatime with your approach or we must wait the end of the audio ? @f-lombardo

**Comment by f-lombardo** [comment]
Hi @ClicShopping , this feature does not provide real time transciption out of the box. It would be really nice a different approach for real time transcription like yours. Feel free to suggest some changes or to submit a PR in this direction, thank you.

**Comment by ClicShopping** [comment]
How do I proceed,
I save little file via an ajax and javascript (button start, stop and ajax relation), each little file is sent to whisper and it transcribe inside a textarea. 
I do not know if this process is inside the idea of this framework but if there is a wish to continue I can share my code.

**Comment by f-lombardo** [comment]
Well, I think that adding JS code to this project isn't a good idea, what's your opinion @MaximeThoonsen ?
Don't you think that such an approach could be translated in some way into PHP code? I mean, splitting the audio in small chunks and giving those back via an iterator or something like this?

**Pull request merged**
